### ISSUE TITLE
setting "python.testing.unittestArgs" results in `TypeError: undefined is not iterable`

### ISSUE THREAD

**Issue by JeroenBos** [kondratyev-nv/vscode-python-test-adapter#133]
The python-test-adapter gives me `Error while loading tests - click to show` when I try to specify arguments to the library `unittest`. 

#### Expected behavior:
No error. 

------

#### Minimal steps to reproduce:

Set the following as vscode settings:
```
{
    "python.testing.unittestArgs": [
        "-s"
    ],
}

```
Restart vscode.
Open vscode to an empty directory in vscode.
Click the python-test-adapter extension.
I get the error `Error while loading tests - click to show`, and when I click, it redirects me to the following output:

```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	at VscodeWorkspaceConfiguration.getUnitTestArguments (/home/jeroen/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.17/out/src/configuration/vscodeWorkspaceConfiguration.js:45:25)
	at VscodeWorkspaceConfiguration.getUnittestConfiguration (/home/jeroen/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.17/out/src/configuration/vscodeWorkspaceConfiguration.js:25:37)
	at PlaceholderAwareWorkspaceConfiguration.getUnittestConfiguration (/home/jeroen/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.17/out/src/configuration/placeholderAwareWorkspaceConfiguration.js:22:45)
	at UnittestTestRunner.<anonymous> (/home/jeroen/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.17/out/src/unittest/unittestTestRunner.js:35:25)
	at Generator.next (<anonymous>)
	at /home/jeroen/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.17/node_modules/tslib/tslib.js:110:75
	at new Promise (<anonymous>)
	at Object.__awaiter (/home/jeroen/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.17/node_modules/tslib/tslib.js:106:16)
	at UnittestTestRunner.load (/home/jeroen/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.17/out/src/unittest/unittestTestRunner.js:34:24)
	at PythonTestAdapter.<anonymous> (/home/jeroen/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.17/out/src/pythonTestAdapter.js:35:65)
	at Generator.next (<anonymous>)
	at /home/jeroen/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.17/node_modules/tslib/tslib.js:110:75
	at new Promise (<anonymous>)
	at Object.__awaiter (/home/jeroen/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.17/node_modules/tslib/tslib.js:106:16)
	at PythonTestAdapter.load (/home/jeroen/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.17/out/src/pythonTestAdapter.js:30:24)
	at TestHub.registerTestAdapter (/home/jeroen/.vscode/extensions/hbenl.vscode-test-explorer-2.17.0/out/hub/testHub.js:56:17)
	at Object.registerTestAdapter (/home/jeroen/.vscode/extensions/hbenl.vscode-test-explorer-2.17.0/out/main.js:80:45)
	at /home/jeroen/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.17/out/src/main.js:25:51
	at Array.forEach (<anonymous>)
	at registerTestAdapters (/home/jeroen/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.17/out/src/main.js:25:14)
	at /home/jeroen/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.17/out/src/main.js:55:34
	at Generator.next (<anonymous>)
	at /home/jeroen/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.17/node_modules/tslib/tslib.js:110:75
	at new Promise (<anonymous>)
	at Object.__awaiter (/home/jeroen/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.17/node_modules/tslib/tslib.js:106:16)
	at activate (/home/jeroen/.vscode/extensions/littlefoxteam.vscode-python-test-adapter-0.3.17/out/src/main.js:43:20)
	at Function._callActivateOptional (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:710:141)
	at Function._callActivate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:709:810)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:708:960
	at async Promise.all (index 0)
```

**Comment by kondratyev-nv** [comment]
@JeroenBos Thank you for the issue! For unittest argument `-s` a value should be provided (start directory), so the configuration should be
```
{
    "python.testing.unittestArgs": [
        "-s",
        "./tests"
    ],
}
```

I will try to make a fix so that the error would be more clear in such case.

**Comment by JeroenBos** [comment]
Yes that works :+1: 

I was missing `"./tests"` because I copied from `python.testing.pytestArgs`, where it's not required. 

Thank you.
