### ISSUE TITLE
Tests not being found

### ISSUE THREAD

**Issue by ChildishGiant** [kondratyev-nv/vscode-python-test-adapter#174]
When I run `py -3 -m pytest` or even just `pytest` it finds my tests fine but when I try to discover new tests it doesn't work. I've changed the root folder to no avail.
```
python c:\Users\allie\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\testing_tools\run_adapter.py discover pytest -- --rootdir e:\code\cloverleaf\web -s unit_tests
Test Discovery failed: 
Error: spawn C:\Users\allie\AppData\Local\Programs\Python\Python37-32\python.exe ENOENT
```

The actual execution of my tests needs to use py 3 but that shouldn't affect the discovery, no?

**Comment by kondratyev-nv** [comment]
@ChildishGiant Thank you for the issue! It looks like the error in the log is produced by Python extension, not the Python Test Explorer. In case you're using Python extension to discover and run your tests, please, report the error to them - https://github.com/Microsoft/vscode-python.

Anyway, if you have [Python Test Explorer](https://marketplace.visualstudio.com/items?itemName=LittleFoxTeam.vscode-python-test-adapter) installed and it does not show any tests, please, look at messages at `Python Test Adapter Log` in the Output section. It would be of help if you show the errors from that log and your settings (like `python.pythonPath`).

**Comment by ChildishGiant** [comment]
It seems to be finding tests in my node_modules, I've tried setting `python.testing.cwd` to the folder my tests are in and adding it to `python.testing.unittestArgs` but neither seem to work. I've also tried all the commited versions of my settings in the past (It used to work flawlessly) but have had no luck. I need to point it to only look in a certain folder but can't seem to get it to

**Comment by kondratyev-nv** [comment]
@ChildishGiant Please, make sure that we're talking about the same extension - [Python Test Explorer](https://marketplace.visualstudio.com/items?itemName=LittleFoxTeam.vscode-python-test-adapter) and consult the Python Test Adapter Log in the Output section to understand better what arguments are used to discover tests.

If this is possible, please, share a reproducible example or at least your settings and folder structure. Also, I can suggest trying to discover tests from the command line first. This can be of help to understand if something is wrong with the extension or your tests.

For unittest I can suggest running the following 
```
python -m unittest discover -v -s <your_test_folder> -p <file_name_pattern_to_discover_tests>
```
For example `python -m unittest discover -v -s tests -p "test_*.py"`

**Comment by ChildishGiant** [comment]
```
PS E:\code\cloverleaf\web\unit_tests> py -3 -m pytest -v -s
=========================================================================================== test session starts ============================================================================================
platform win32 -- Python 3.7.4, pytest-5.4.3, py-1.8.0, pluggy-0.13.0 -- C:\Users\allie\AppData\Local\Programs\Python\Python37-32\python.exe
cachedir: .pytest_cache
rootdir: E:\code\cloverleaf\web\unit_tests
collecting ... E:\code\cloverleaf\web\unit_tests
collected 5 items
```

The Python Test Adapter Log is empty but the Python Test Log says this:
```
python c:\Users\allie\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\testing_tools\run_adapter.py discover pytest -- --rootdir e:\code\cloverleaf\web -s --cache-clear
Test Discovery failed: 
Error: ============================= test session starts =============================
platform win32 -- Python 3.7.4, pytest-5.4.3, py-1.8.0, pluggy-0.13.0
rootdir: e:\code\cloverleaf\web
collected 0 items / 9 errors

=================================== ERRORS ====================================
______ ERROR collecting node_modules/cloverleaf/unit_tests/test_main.py _______
node_modules\cloverleaf\unit_tests\test_main.py:9: in <module>
    with open("../data/sites.json", 'r') as json_file:
E   FileNotFoundError: [Errno 2] No such file or directory: '../data/sites.json'
__ ERROR collecting node_modules/node-gyp/gyp/pylib/gyp/MSVSSettings_test.py __
C:\Users\allie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\python.py:511: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
C:\Users\allie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py\_path\local.py:701: in pyimport
    __import__(modname)
E     File "E:\code\cloverleaf\web\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 37
E       print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
E                            ^
E   SyntaxError: invalid syntax
_____ ERROR collecting node_modules/node-gyp/gyp/pylib/gyp/common_test.py _____
C:\Users\allie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\python.py:511: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
C:\Users\allie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py\_path\local.py:701: in pyimport
    __import__(modname)
E     File "E:\code\cloverleaf\web\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 37
E       print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
E                            ^
E   SyntaxError: invalid syntax
____ ERROR collecting node_modules/node-gyp/gyp/pylib/gyp/easy_xml_test.py ____
C:\Users\allie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\python.py:511: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
C:\Users\allie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py\_path\local.py:701: in pyimport
    __import__(modname)
E     File "E:\code\cloverleaf\web\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 37
E       print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
E                            ^
E   SyntaxError: invalid syntax
_____ ERROR collecting node_modules/node-gyp/gyp/pylib/gyp/input_test.py ______
C:\Users\allie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\python.py:511: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
C:\Users\allie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py\_path\local.py:701: in pyimport
    __import__(modname)
E     File "E:\code\cloverleaf\web\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 37
E       print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
E                            ^
E   SyntaxError: invalid syntax
_ ERROR collecting node_modules/node-gyp/gyp/pylib/gyp/generator/msvs_test.py _
C:\Users\allie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\python.py:511: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
C:\Users\allie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py\_path\local.py:701: in pyimport
    __import__(modname)
E     File "E:\code\cloverleaf\web\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 37
E       print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
E                            ^
E   SyntaxError: invalid syntax
_ ERROR collecting node_modules/node-gyp/gyp/pylib/gyp/generator/ninja_test.py _
C:\Users\allie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\python.py:511: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
C:\Users\allie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py\_path\local.py:701: in pyimport
    __import__(modname)
E     File "E:\code\cloverleaf\web\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 37
E       print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
E                            ^
E   SyntaxError: invalid syntax
_ ERROR collecting node_modules/node-gyp/gyp/pylib/gyp/generator/xcode_test.py _
C:\Users\allie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\python.py:511: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
C:\Users\allie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py\_path\local.py:701: in pyimport
    __import__(modname)
E     File "E:\code\cloverleaf\web\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 37
E       print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
E                            ^
E   SyntaxError: invalid syntax
__________________ ERROR collecting unit_tests/test_main.py ___________________
unit_tests\test_main.py:26: in <module>
    with open("../node_modules/cloverleaf/data/sites.json", 'r') as json_file:
E   FileNotFoundError: [Errno 2] No such file or directory: '../node_modules/cloverleaf/data/sites.json'
=========================== short test summary info ===========================
ERROR node_modules/cloverleaf/unit_tests/test_main.py - FileNotFoundError: [E...
ERROR node_modules/node-gyp/gyp/pylib/gyp/MSVSSettings_test.py
ERROR node_modules/node-gyp/gyp/pylib/gyp/common_test.py
ERROR node_modules/node-gyp/gyp/pylib/gyp/easy_xml_test.py
ERROR node_modules/node-gyp/gyp/pylib/gyp/input_test.py
ERROR node_modules/node-gyp/gyp/pylib/gyp/generator/msvs_test.py
ERROR node_modules/node-gyp/gyp/pylib/gyp/generator/ninja_test.py
ERROR node_modules/node-gyp/gyp/pylib/gyp/generator/xcode_test.py
ERROR unit_tests/test_main.py - FileNotFoundError: [Errno 2] No such file or ...
!!!!!!!!!!!!!!!!!!! Interrupted: 9 errors during collection !!!!!!!!!!!!!!!!!!!
============================= 9 errors in 21.77s ==============================

Traceback (most recent call last):
  File "c:\Users\allie\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\testing_tools\run_adapter.py", line 22, in <module>
    main(tool, cmd, subargs, toolargs)
  File "c:\Users\allie\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\testing_tools\adapter\__main__.py", line 100, in main
    parents, result = run(toolargs, **subargs)
  File "c:\Users\allie\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\testing_tools\adapter\pytest\_discovery.py", line 44, in discover
    raise Exception("pytest discovery failed (exit code {})".format(ec))
Exception: pytest discovery failed (exit code 2)
```

I think I need to setup the directory properly but all the documented settings aren't working

**Comment by kondratyev-nv** [comment]
@ChildishGiant I believe you're working with https://github.com/cloverleaf/web repository. I've tried it myself and with a little bit of changing the settings it looks like it works
<img width="797" alt="image" src="https://user-images.githubusercontent.com/4085884/89669305-e50b7600-d8e7-11ea-962b-2f4b4a3fb7fc.png">

```
```
I've customized `python.pythonPath`

**Comment by ChildishGiant** [comment]
Thanks for all the help on this issue, that seems to have fixed it but it took a while of entering it and removing it before it worked.
