### ISSUE TITLE
Split test log view per test

### ISSUE THREAD

**Issue by GuillaumeDesforges** [kondratyev-nv/vscode-python-test-adapter#259]
When I was using the extension not so long ago, clicking on a test in the test discovery panel would display the log of a specific test.
Now all my test logs are together in "Python Test Log"

Could it be possible to display logs only for a specific test?

**Comment by kondratyev-nv** [comment]
@GuillaumeDesforges Thank you for the issue! The "Python Test Log" belongs to the Python extension, not the Python Test Explorer. In case you're using Python extension to discover and run your tests, please, report the error to them - https://github.com/Microsoft/vscode-python.

I've double checked this for Python Test Explorer and output looks correct (error only for the test selected in UI), notice that output is from Test Explorer log
<img width="783" alt="image" src="https://user-images.githubusercontent.com/4085884/124298049-79b43d80-db64-11eb-82a2-bcaf9e3d8566.png">
So maybe you can try using Python Test Explorer  instead 🙂

**Comment by GuillaumeDesforges** [comment]
Thanks for your reply. Though I do use Test Explorer
![image](https://user-images.githubusercontent.com/1882000/124299822-26d78780-db5e-11eb-9e22-e9b1bc5e8bbd.png)

Maybe an issue with the Test Explorer UI itself then. I'll investigate.

**Comment by kondratyev-nv** [comment]
@GuillaumeDesforges if you have it installed, it does not mean you're using it to discover and run your tests 🙂 The Python extension provides its own functionality and UI for tests. It's shown at the same panel as Test Explorer UI (this extension provides UI for Python Test Explorer). When both extensions active and can detect some tests you'll see two sections, like this (one might be collapsed)
<img width="476" alt="image" src="https://user-images.githubusercontent.com/4085884/124304091-ea128d00-db6b-11eb-966b-f0e9f7ae14c3.png">

If you don't see Test Explorer that might indicate that there are some issues with test discovery. I can try helping you investigate further if that's the case.

If that's ok with you, you can send a screenshot or maybe some additional information (like your settings), that might help diagnose the issue better.

**Comment by GuillaumeDesforges** [comment]
Hey, thanks for taking this issue!

Here is a screenshot for me:
![image](https://user-images.githubusercontent.com/1882000/124731780-d58b1780-df12-11eb-9680-1a27d291ed38.png)

It would be helpful if we could get it fixed!

**Comment by kondratyev-nv** [comment]
@GuillaumeDesforges This looks like testing UI from the Python extension. To make sure you're using Python Test Explorer (this extension) you can try disabling testing functionality from the Python extension like in this section of the README - https://github.com/kondratyev-nv/vscode-python-test-adapter#1-disable-duplicated-code-lenses. Let me know if this helps and whether you see any tests from Python Test Explorer.

**Comment by GuillaumeDesforges** [comment]
Thanks, I put those settings as suggested, now I don't have any test panel appearing. From the logs I get

```
[2021-07-12 12:52:29.287] [exthost] [error] Activating extension ms-vscode.test-adapter-converter failed due to an error:
[2021-07-12 12:52:29.287] [exthost] [error] /home/arsleust/.vscode-server-insiders/extensions/ms-vscode.test-adapter-converter-0.0.12/out/extension.js:1
var E=Object.create,u=Object.defineProperty,x=Object.getPrototypeOf,w=Object.prototype.hasOwnProperty,S=Object.getOwnPropertyNames,R=Object.getOwnPropertyDescriptor;var g=r=>u(r,"__esModule",{value:!0});var k=(r,e)=>()=>(e||r((e={exports:{}}).exports,e),e.exports),A=(r,e)=>{for(var t in e)u(r,t,{get:e[t],enumerable:!0})},B=(r,e,t)=>{if(e&&typeof e=="object"||typeof e=="function")for(let o of S(e))!w.call(r,o)&&o!=="default"&&u(r,o,{get:()=>e[o],enumerable:!(t=R(e,o))||t.enumerable});return r},v=r=>B(g(u(r!=null?E(x(r)):{},"default",r&&r.__esModule&&"default"in r?{get:()=>r.default,enumerable:!0}:{value:r,enumerable:!0})),r);var m=k(f=>{"use strict";Object.defineProperty(f,"__esModule",{value:!0});f.testExplorerExtensionId=void 0;f.testExplorerExtensionId="hbenl.vscode-test-explorer"});g(exports);A(exports,{activate:()=>W});var p=v(require("vscode")),M=v(m());var C=v(require("vscode"));var a=v(require("vscode")),D=0,U=0,h=class{constructor(e,t){this.adapter=e;this.ctrl=t;this.itemsById=new Map;this.tasksByRunId=new Map;this.disposables=[];this.root=this.ctrl.createTestItem(`test-adapter-root-${U++}`,"Test Adapter",this.ctrl.root,void 0,{generation:0,converter:this}),this.root.debuggable=!0,this.itemsById.set(this.root.id,this.root),this.disposables.push(this.root,e.tests(o=>{switch(o.type){case"finished":this.root.busy=!1,o.suite&&(this.syncItemChildren(this.root,D++,[o.suite]),F());break;case"started":this.root.busy=!0;break}}),e.testStates(o=>{let s=this.tasksByRunId.get(o.testRunId??"");if(!!s)switch(o.type){case"test":return this.onTestEvent(s,o);case"suite":return;case"finished":return s.end()}})),e.retire&&this.disposables.push(e.retire(o=>{for(let s of o.tests??[this.root.id])this.itemsById.get(s)?.invalidate()})),setTimeout(()=>this.adapter.load(),1)}async refresh(){this.root.busy=!0,await this.adapter.load(),this.root.busy=!1}dispose(){this.disposables.forEach(e=>e.dispose())}async run(e,t,o,s){t.includes(this.root)&&(t=[...this.root.children.values()]);let i,n=await new Promise(l=>{i=this.adapter.testStates(c=>{c.type==="started"&&(l(c),i.dispose())}),o?this.adapter.debug?this.adapter.debug(t.map(c=>c.id)):l(void 0):this.adapter.run(t.map(c=>c.id))}).finally(()=>i.dispose());if(!n)return;let d=[t];for(;d.length;)for(let l of d.pop())e.setState(l,a.TestResultState.Queued),d.push(l.children.values());this.tasksByRunId.set(n.testRunId??"",e),s.onCancellationRequested(()=>this.adapter.cancel())}addItem(e,t,o){let s=o.children.get(e.id);return s?s.data.generation=t:(s=this.ctrl.createTestItem(e.id,e.label,o,e.file?I(e.file):o.uri,{converter:this,generation:t}),this.itemsById.set(e.id,s)),s.description=e.description,e.line!==void 0&&(s.range=new a.Range(e.line,0,e.line+1,0)),s.description=e.description,s.debuggable=!!this.adapter.debug,e.errored&&(s.error=e.message),this.syncItemChildren(s,t,"children"in e?e.children:[]),s}syncItemChildren(e,t,o){for(let s of o)this.addItem(s,t,e);for(let s of e.children.values())s.data.generation!==t&&(s.dispose(),this.itemsById.delete(s.id))}onTestEvent(e,t){let o=typeof t.test=="string"?t.test:t.test.id,s=this.itemsById.get(o);if(!!s){if(t.message){let i=new a.TestMessage(t.message);i.severity=a.TestMessageSeverity.Information,e.appendMessage(s,i)}for(let i of t.decorations??[]){let n=new a.TestMessage(i.message),d=i.file?I(i.file):s.uri;d&&(n.location=new a.Location(d,new a.Position(i.line,0))),e.appendMessage(s,n)}e.setState(s,P[t.state])}}},H=/^[a-z][a-z0-9+-.]+:/,I=r=>H.test(r)?a.Uri.parse(r):a.Uri.file(r),P={running:a.TestResultState.Running,passed:a.TestResultState.Passed,failed:a.TestResultState.Failed,skipped:a.TestResultState.Skipped,errored:a.TestResultState.Errored,completed:a.TestResultState.Unset},b=["testExplorer.gutterDecoration","testExplorer.codeLens","testExplorer.errorDecoration","testExplorer.errorDecorationHover"],y=a.workspace.getConfiguration().get(b[0])!==!1,F=async()=>{if(!y)return;y=!1;let r="Yes",e="Only in this Workspace",t="No",o=await a.window.showInformationMessage("Thanks for trying out native VS Code testing! Would you like to disable the default Test Explorer extension UI?",t,r,e);if(o===r||o===e){let s=o===r?a.ConfigurationTarget.Global:a.ConfigurationTarget.Workspace,i=a.workspace.getConfiguration();for(let n of b)i.update(n,!1,s)}};var T=class{constructor(){this.converters=new Map}registerTestAdapter(e){this.ctrl??=this.makeTestController(),this.converters.set(e,new h(e,this.ctrl))}unregisterTestAdapter(e){this.converters.get(e)?.dispose(),this.converters.delete(e)}dispose(){this.ctrl?.dispose();for(let e of this.converters.values())e.dispose()}refresh(e){for(let t of this.converters.values())(!e||t.root.id===e.id)&&t.refresh()}makeTestController(){let e=C.test.createTestController("ms-vscode.test-adapter-converter");return e.root.label="Test Adapter Converter",e.root.debuggable=!0,e.runHandler=(t,o)=>{if(t.tests.includes(e.root)){for(let i of this.converters.values())i.run(e.createTestRun(t),[i.root],t.debug,o);return}let s=new Map;for(let i of t.tests){let n=s.get(i.data.converter);n?n.push(i):s.set(i.data.converter,[i])}for(let[i,n]of s)i.run(e.createTestRun(t),n,t.debug,o)},e}};function W(r){let e;r.subscriptions.push(p.commands.registerCommand("testExplorerConverter.activate",()=>{let t=p.extensions.getExtension(M.testExplorerExtensionId);if(!t)return;let o=t.exports;e=new T,r.subscriptions.push(e),o.registerTestController(e),r.subscriptions.push({dispose(){o.unregisterTestController(e)}})}),p.commands.registerCommand("testExplorerConverter.refreshAdapter",t=>{e?.refresh(t)}))}0&&(module.exports={activate});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

SyntaxError: Unexpected token '??='
	at wrapSafe (internal/modules/cjs/loader.js:979:16)
	at Module._compile (internal/modules/cjs/loader.js:1027:27)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
	at Module.load (internal/modules/cjs/loader.js:928:32)
	at Function.Module._load (internal/modules/cjs/loader.js:769:14)
	at Function.s._load (/home/arsleust/.vscode-server-insiders/bin/1db97b8c87fb32aa47b58135832733f4950362b4/out/vs/server/remoteExtensionHostProcess.js:103:27800)
	at Function.b._load (/home/arsleust/.vscode-server-insiders/bin/1db97b8c87fb32aa47b58135832733f4950362b4/out/vs/server/remoteExtensionHostProcess.js:103:24471)
	at Function.l._load (/home/arsleust/.vscode-server-insiders/bin/1db97b8c87fb32aa47b58135832733f4950362b4/out/vs/server/remoteExtensionHostProcess.js:93:59004)
	at Module.require (internal/modules/cjs/loader.js:952:19)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.t [as __$__nodeRequire] (/home/arsleust/.vscode-server-insiders/bin/1db97b8c87fb32aa47b58135832733f4950362b4/out/vs/loader.js:5:101)
	at c._loadCommonJSModule (/home/arsleust/.vscode-server-insiders/bin/1db97b8c87fb32aa47b58135832733f4950362b4/out/vs/server/remoteExtensionHostProcess.js:103:25877)
	at c._doActivateExtension (/home/arsleust/.vscode-server-insiders/bin/1db97b8c87fb32aa47b58135832733f4950362b4/out/vs/server/remoteExtensionHostProcess.js:89:12556)
	at c._activateExtension (/home/arsleust/.vscode-server-insiders/bin/1db97b8c87fb32aa47b58135832733f4950362b4/out/vs/server/remoteExtensionHostProcess.js:89:11657)
	at Object.actualActivateExtension (/home/arsleust/.vscode-server-insiders/bin/1db97b8c87fb32aa47b58135832733f4950362b4/out/vs/server/remoteExtensionHostProcess.js:89:9202)
	at d._activateExtension (/home/arsleust/.vscode-server-insiders/bin/1db97b8c87fb32aa47b58135832733f4950362b4/out/vs/server/remoteExtensionHostProcess.js:84:97724)
	at /home/arsleust/.vscode-server-insiders/bin/1db97b8c87fb32aa47b58135832733f4950362b4/out/vs/server/remoteExtensionHostProcess.js:84:97406
	at Array.map (<anonymous>)
	at d._activateExtensions (/home/arsleust/.vscode-server-insiders/bin/1db97b8c87fb32aa47b58135832733f4950362b4/out/vs/server/remoteExtensionHostProcess.js:84:97394)
	at d._activateExtensions (/home/arsleust/.vscode-server-insiders/bin/1db97b8c87fb32aa47b58135832733f4950362b4/out/vs/server/remoteExtensionHostProcess.js:84:97459)
	at d.activateByEvent (/home/arsleust/.vscode-server-insiders/bin/1db97b8c87fb32aa47b58135832733f4950362b4/out/vs/server/remoteExtensionHostProcess.js:84:94728)
	at c._activateByEvent (/home/arsleust/.vscode-server-insiders/bin/1db97b8c87fb32aa47b58135832733f4950362b4/out/vs/server/remoteExtensionHostProcess.js:89:10141)
	at c._handleEagerExtensions (/home/arsleust/.vscode-server-insiders/bin/1db97b8c87fb32aa47b58135832733f4950362b4/out/vs/server/remoteExtensionHostProcess.js:89:15538)
	at /home/arsleust/.vscode-server-insiders/bin/1db97b8c87fb32aa47b58135832733f4950362b4/out/vs/server/remoteExtensionHostProcess.js:89:17891
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by GuillaumeDesforges** [comment]
Weirdly enough, it is fixed now without anything done on my side. Maybe a VSCode update?
